FROM jupyterhub/k8s-hub:0.8.2
# Patching Jupyter Login
COPY login.html /usr/local/share/jupyterhub/templates/login.html
COPY notebook.png /usr/local/share/jupyterhub/static/images/jupyter.png
COPY notebook.png /usr/local/share/jupyterhub/static/favicon.ico
